/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.ieselcaminas.mileskilometers;

import java.awt.Dialog;
import javax.swing.JOptionPane;

/**
 *
 * @author alu10191634
 */
public class MainFrame extends javax.swing.JFrame {
    
    public static final double KMS_PER_MILE = 1.60934; 
   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMiles = new javax.swing.JLabel();
        labelKms = new javax.swing.JLabel();
        TextFieldMiles = new javax.swing.JTextField();
        TextFieldKms = new javax.swing.JTextField();
        ButtonConvertToKms = new javax.swing.JButton();
        ButtonConvertToMiles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        labelMiles.setText("Miles");

        labelKms.setText("Kilometers");

        ButtonConvertToKms.setText("Convert");
        ButtonConvertToKms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvertToKmsActionPerformed(evt);
            }
        });

        ButtonConvertToMiles.setText("Convert");
        ButtonConvertToMiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvertToMilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelKms)
                    .addComponent(labelMiles))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldMiles, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(TextFieldKms))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonConvertToMiles)
                    .addComponent(ButtonConvertToKms))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMiles)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldMiles, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonConvertToKms)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelKms))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldKms)
                            .addComponent(ButtonConvertToMiles))))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void ButtonConvertToKmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvertToKmsActionPerformed
        // TODO add your handling code here:
        String text = TextFieldMiles.getText();
        try {
        double miles = Double.parseDouble(text);
        double kms = miles * KMS_PER_MILE;
        TextFieldKms.setText("" + kms);
        } catch(NumberFormatException ex) {
            showMessageOnlyNumber();
        }
    }//GEN-LAST:event_ButtonConvertToKmsActionPerformed

    private void ButtonConvertToMilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvertToMilesActionPerformed
        // TODO add your handling code here:  
        String text = TextFieldKms.getText();
        try {
        double kms = Double.parseDouble(text);
        double miles = kms/KMS_PER_MILE;
        TextFieldMiles.setText("" + miles);
        } catch(NumberFormatException ex) {
            showMessageOnlyNumber();
        }
    }//GEN-LAST:event_ButtonConvertToMilesActionPerformed

    private void showMessageOnlyNumber(){
    JOptionPane.showMessageDialog(null, "Only numbers");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConvertToKms;
    private javax.swing.JButton ButtonConvertToMiles;
    private javax.swing.JTextField TextFieldKms;
    private javax.swing.JTextField TextFieldMiles;
    private javax.swing.JLabel labelKms;
    private javax.swing.JLabel labelMiles;
    // End of variables declaration//GEN-END:variables
}
